[Implementación Swagger] - Implementation swagger
wolox-training/af-java pull request #10
Opened 2020-03-13 15:37 UTC by AleFalcon

## Summary
Implementatio Swagger for documentation of the API

## Trello Card
https://trello.com/c/56TiirpO/40-swagger

2020-03-18 20:01 UTC, Gianni-Nicolas requested changes
Great Job

2020-03-18 20:01 UTC, Gianni-Nicolas commented on src/main/java/wolox/training/controllers/BookApiController.java
> +    @ApiOperation(value = "Given a book, create one, and return the book.", response = Book.class)
You could add @ApiResponses to register the possible httpStatus of each controller.

2020-03-18 20:01 UTC, Gianni-Nicolas commented on src/main/java/wolox/training/controllers/BookApiController.java
> +    @ApiOperation(value = "Given the isbn of the book, you can update the book, and return the book.", response = Book.class)
The same as previously commented.

2020-03-18 20:01 UTC, Gianni-Nicolas commented on src/main/java/wolox/training/controllers/BookApiController.java
> +    @ApiOperation(value = "Given the isbn of the book, you delete the book, and return void", response = void.class)
The same as previously commented

2020-03-18 20:01 UTC, Gianni-Nicolas commented on src/main/java/wolox/training/controllers/BookApiController.java
> +    @ApiOperation(value = "Given the isbn of the book, return the book asked", response = Book.class)
The same as previously commented

2020-03-18 20:01 UTC, Gianni-Nicolas commented on src/main/java/wolox/training/controllers/UserApiController.java
> +    @ApiOperation(value = "Given a user, create one, and return the user.", response = User.class)
You could add @ApiResponses to register the possible httpStatus of each controller.

2020-03-18 20:01 UTC, Gianni-Nicolas commented on src/main/java/wolox/training/controllers/UserApiController.java
> +    @ApiOperation(value = "Given the username of a user, you can update the user, and return the user.", response = User.class)
The same as previously commented

2020-03-18 20:01 UTC, Gianni-Nicolas commented on src/main/java/wolox/training/controllers/UserApiController.java
> +    @ApiOperation(value = "Given the username of a user, you delete the user, and return void", response = void.class)
The same as previously commented

2020-03-18 20:01 UTC, Gianni-Nicolas commented on src/main/java/wolox/training/controllers/UserApiController.java
> +    @ApiOperation(value = "Given the username of a user, return the user asked", response = User.class)
The same as previously commented

2020-03-18 20:01 UTC, Gianni-Nicolas commented on src/main/java/wolox/training/controllers/UserApiController.java
> +    @ApiOperation(value = "Given the username of a user, return a book list of the user", response = Book.class)
The same as previously commented

2020-03-18 20:01 UTC, Gianni-Nicolas commented on src/main/java/wolox/training/controllers/UserApiController.java
> +    @ApiOperation(value = "Given the username of a user and the isbn of a book, the book is added to user, return the user", response = void.class)
The same as previously commented

2020-03-18 20:01 UTC, Gianni-Nicolas commented on src/main/java/wolox/training/models/Book.java
> +    @ApiModelProperty(notes = "The book genre: could be horror, comedy, drama, etc")
You can add the examples as follows:
`@ApiModelProperty(notes = "genre", example = "Horror")`

And in the mandatory fields you can add the following:
`@ApiModelProperty(notes = "genre", required = true, example = "Horror")`

2020-03-18 20:01 UTC, Gianni-Nicolas commented on src/main/java/wolox/training/models/User.java
Add swagger to user model

2020-03-18 20:01 UTC, Gianni-Nicolas commented on src/main/java/wolox/training/models/Book.java
Add swagger to the rest of the fields of the book model

2020-03-19 15:33 UTC, Gianni-Nicolas submitted a review, later dismissed

2020-03-19 20:08 UTC, Gianni-Nicolas submitted a review, later dismissed

2020-03-20 14:24 UTC, Gianni-Nicolas submitted a review, later dismissed

2020-03-20 15:35 UTC, facucompe requested changes

2020-03-20 15:35 UTC, facucompe commented on src/main/java/wolox/training/utils/ErrorConstants.java
> +  public static String NOT_EMPTY_GENRE = "The genre field cannot be empty.";
You can implement a generic string here. Something like this :
`The %s field cannot be empty`
And then do:
`String.format(ErrorConstants.fieldEmpty, "genre")`

2020-03-20 16:48 UTC, AleFalcon reviewed
Okay

2020-03-25 18:15 UTC, Gianni-Nicolas approved these changes

2020-04-01 15:49 UTC, facucompe approved these changes

2020-04-01 18:13 UTC, merged