[Implementacion JUnit] - Implementation JUnit
wolox-training/af-java pull request #12
Opened 2020-03-20 20:56 UTC by AleFalcon

## Summary
Implementatio JUnit, with creation test for user and books controllers, and model.

## Trello Card
https://trello.com/c/jbkhpnh6/28-junit-testing

2020-03-26 20:02 UTC, Gianni-Nicolas submitted a review, later dismissed

2020-04-01 14:36 UTC, facucompe requested changes

2020-04-01 14:36 UTC, facucompe commented on src/main/java/wolox/training/models/Book.java
> +    public boolean equal_book (Book book){
You should overrride the method `equals()`

2020-04-01 14:36 UTC, facucompe commented on src/test/java/wolox/training/controllers/BookTest.java
> +        .content("{\"genre\": \"Terror\","
Try to use an object mapper instead https://mkyong.com/java/jackson-2-convert-java-object-to-from-json/ .
Or use jsonPath https://mkyong.com/spring-boot/spring-test-how-to-test-a-json-array-in-jsonpath/

2020-04-01 14:36 UTC, facucompe commented on src/test/java/wolox/training/controllers/BookTest.java
> +public class BookTest {
`BookControllerTest`

2020-04-01 14:36 UTC, facucompe commented on src/test/java/wolox/training/controllers/UserTest.java
> +public class UserTest {
`UserControllerTest`

2020-04-01 14:36 UTC, facucompe commented on src/test/java/wolox/training/models/BookTest.java
> +    bookRepository.save(book);
Use `entityManager` instead. 
```
entityManager.persist(book);
entityManager.flush();
```

2020-04-01 14:36 UTC, facucompe commented on src/test/java/wolox/training/models/BookTest.java
> +    bookRepository.save(book);
You can move it to a method with `@Before`

2020-04-01 18:10 UTC, AleFalcon reviewed
Corrections

2020-04-02 18:10 UTC, facucompe requested changes

2020-04-02 18:10 UTC, facucompe commented on src/test/java/wolox/training/models/UserModelTest.java
> +    userRepository.save(user);
You should use entityManager here too

2020-04-03 00:12 UTC, AleFalcon reviewed
Ready

2020-04-08 15:02 UTC, facucompe approved these changes

2020-04-08 16:05 UTC, Gianni-Nicolas approved these changes

2020-04-08 16:33 UTC, merged