Implement spring security
wolox-training/af-java pull request #13
Opened 2020-03-25 17:56 UTC by AleFalcon

Summary
Implementatio Spring Security

Trello Card
https://trello.com/c/ou1JalCC/23-integrar-spring-security

2020-04-08 15:48 UTC, facucompe requested changes

2020-04-08 15:48 UTC, facucompe commented on src/main/java/wolox/training/config/SetupDataLoader.java
> +public class SetupDataLoader implements
I would create a data.sql file instead a class to initialize this information

2020-04-08 15:48 UTC, facucompe commented on src/main/java/wolox/training/config/SpringBootSecurityApplication.java
> +public class SpringBootSecurityApplication {
You alreary have an main. Remove this.

2020-04-08 15:48 UTC, facucompe commented on src/main/java/wolox/training/utils/CustomAuthenticationProvider.java
> +    return new UsernamePasswordAuthenticationToken(
You don't check if the password is the correct one.  Add this: 
`@Autowired
    private PasswordEncoder passwordEncoder;`

2020-04-09 17:03 UTC, AleFalcon reviewed
Reay

2020-04-15 18:48 UTC, facucompe submitted a review, later dismissed

2020-04-17 15:01 UTC, Gianni-Nicolas requested changes
Great Job

2020-04-17 15:01 UTC, Gianni-Nicolas commented on src/main/java/wolox/training/models/User.java
> +    private String password;
Add the following property so that the password cannot be read:

@JsonProperty(access = Access.WRITE_ONLY)

2020-04-17 15:01 UTC, Gianni-Nicolas commented on src/main/java/wolox/training/controllers/UserController.java
> +    @GetMapping("/login")
Normally in common strategies when REST is applied, the url used to refer to a controller that brings the logged user information is as follows:

"/me" or "/user".

2020-04-17 17:01 UTC, AleFalcon reviewed
Ready

2020-04-17 17:41 UTC, Gianni-Nicolas submitted a review, later dismissed

2020-04-20 13:07 UTC, facucompe submitted a review, later dismissed

2020-04-20 14:58 UTC, facucompe approved these changes

2020-04-20 15:00 UTC, Gianni-Nicolas approved these changes

2020-04-20 15:00 UTC, merged