[Implementacion Servicio Externo] - External service
wolox-training/af-java pull request #14
Opened 2020-03-26 18:42 UTC by AleFalcon

## Summary
Implementatio External Services, OpenLibrary

## Trello Card
https://trello.com/c/H6MKvu0u/22-integraci%C3%B3n-api-externa

2020-04-08 16:09 UTC, facucompe requested changes

2020-04-08 16:09 UTC, facucompe commented on src/main/java/wolox/training/adapters/BookAdapter.java
> +public class BookAdapter {
Add `@Component` so you can use `@Autowired` in the service

2020-04-08 16:09 UTC, facucompe commented on src/main/java/wolox/training/adapters/BookAdapter.java
> +    return new BookDTO(isbn, title, subtitle, publishers, publishDate,
Instantiate the book and then use setters. Don't create a variable for every attribute

2020-04-08 16:09 UTC, facucompe commented on src/main/java/wolox/training/adapters/BookAdapter.java
> +        Integer
You first convert it from string to int in line 14.

2020-04-08 16:09 UTC, facucompe commented on src/main/java/wolox/training/external/dtos/BookDTO.java
> +      String subtitle) {
Look out for unnecessary line jumps

2020-04-08 16:09 UTC, facucompe commented on src/main/java/wolox/training/controllers/ApiController.java
> +    @ApiOperation(value = "Given the isbn of a book, search in DB or external service and return the book or an exception", response = User.class)
This should not be in the ApiController

2020-04-08 16:09 UTC, facucompe commented on src/main/java/wolox/training/controllers/BookController.java
> +    private OpenLibraryService openLibraryService = new OpenLibraryService();
Use `@Autowired` annotation

2020-04-08 16:09 UTC, facucompe commented on src/main/java/wolox/training/external/services/OpenLibraryService.java
> +public class OpenLibraryService {
Use `@Service` so you can use  `@Autowired` in the controller

2020-04-08 16:09 UTC, facucompe commented on src/main/java/wolox/training/utils/VariablesConstants.java
> +  public static String OPEN_LIBRARY_URL = "https://openlibrary.org/api/books?bibkeys=ISBN:%s&format=json&jscmd=data";
`https://openlibrary.org/api` should be a property. Use `@Value` https://www.baeldung.com/spring-value-annotation

2020-04-08 16:09 UTC, facucompe commented on src/main/java/wolox/training/utils/VariablesConstants.java
> +  public static String OPEN_LIBRARY_URL = "https://openlibrary.org/api/books?bibkeys=ISBN:%s&format=json&jscmd=data";
Leave `/books?bibkeys=ISBN:%s&format=json&jscmd=data` as a constant

2020-04-08 16:09 UTC, facucompe commented on src/main/java/wolox/training/external/services/OpenLibraryService.java
> +      return bookAdapter.transformBookDTOToBook(bookDTO);
No need to use a  intermediate DTO here. Delete `BookDTO`

2020-04-08 16:11 UTC, facucompe commented on src/main/java/wolox/training/external/services/OpenLibraryService.java
> +      String isbn) {
Same  in this method. Unnecessary line jumps make code really difficult to read.

2020-04-13 16:30 UTC, AleFalcon reviewed
Ready

2020-04-15 18:53 UTC, facucompe requested changes

2020-04-15 18:53 UTC, facucompe commented on src/main/java/wolox/training/external/services/OpenLibraryService.java
> +  @Value("https://openlibrary.org/api/books?bibkeys=ISBN:")
`@Value("${openlibrary.baseUrl}")` and add it to your application properties

2020-04-15 22:41 UTC, AleFalcon reviewed
Ready

2020-04-16 13:06 UTC, facucompe approved these changes

2020-04-17 04:58 UTC, Gianni-Nicolas approved these changes
Great Job

2020-04-20 14:56 UTC, merged