[Metodos Para Repositorios] - Methods for repository of user and book
wolox-training/af-java pull request #16
Opened 2020-04-07 14:40 UTC by AleFalcon

## Summary
Create methods for filter for users and books.

## Trello Card
https://trello.com/c/jeBbZeES/25-agregar-m%C3%A9todos-m%C3%A1s-complejos-a-los-repositorios

2020-04-15 19:07 UTC, facucompe requested changes

2020-04-15 19:07 UTC, facucompe commented on src/main/java/wolox/training/controllers/ApiController.java
> +    @ApiOperation(value = "Given the editor of the book, return the books or an exception", response = User.class)
All this methods should be in a service, not in Api controller.

2020-04-15 23:00 UTC, AleFalcon reviewed
Ready

2020-04-17 05:01 UTC, Gianni-Nicolas approved these changes

2020-04-20 13:07 UTC, facucompe approved these changes

2020-04-20 14:55 UTC, merged