[Query Manual] - Query custom for books
wolox-training/af-java pull request #17
Opened 2020-04-07 18:25 UTC by AleFalcon

## Summary
Create query custom for books, for filter this.

## Trello Card
https://trello.com/c/U9IiggGo/30-queries-custom-en-repositorio

2020-04-15 19:17 UTC, facucompe requested changes

2020-04-15 19:17 UTC, facucompe commented on src/main/java/wolox/training/repositories/BookRepository.java
> +        nativeQuery = true)
Try not using native query

2020-04-15 19:17 UTC, facucompe commented on src/main/java/wolox/training/repositories/BookRepository.java
> +    @Query(value = "SELECT * FROM BOOKS B WHERE B.PUBLISHER = ?1 OR B.GENRE = ?2 OR B.YEAR = ?3",
What if any of this parameters are null

2020-04-15 19:17 UTC, facucompe commented on src/main/java/wolox/training/repositories/BookRepository.java
> +    @Query(value = "SELECT * FROM BOOKS B WHERE B.PUBLISHER = ?1 OR B.GENRE = ?2 OR B.YEAR = ?3",
You can do 
```
SELECT * FROM books
WHERE 
(:publisher is null OR publisher = :publisher) AND
(:genre is null OR genre = :genre) AND ...
```

2020-04-15 19:17 UTC, facucompe commented on src/main/java/wolox/training/repositories/BookRepository.java
> +    List<Book> findAllBooksWithFilter(String editor, String genre, String year);
Use `@Param("editor")` annotation so you can use `:editor` instead of `?1`

2020-04-16 15:17 UTC, AleFalcon reviewed
Ready

2020-04-20 13:07 UTC, Gianni-Nicolas approved these changes

2020-04-20 13:08 UTC, facucompe approved these changes

2020-04-20 14:54 UTC, merged