[Creacion de Repositorio de Usuarios] - Create user repository
wolox-training/af-java pull request #7
Opened 2020-03-10 18:10 UTC by AleFalcon

## Summary
Create user repository with method for find books by author

## Trello Card
https://trello.com/c/cLmHFmDx/20-crear-un-repositorio-de-users

2020-03-12 15:51 UTC, facucompe requested changes

2020-03-12 15:51 UTC, facucompe commented on src/main/java/wolox/training/repositories/UserRepository.java
> +    User findOneByName(String name);
```suggestion
    Optional<User> findOneByName(String name);
```

2020-03-13 15:14 UTC, Gianni-Nicolas approved these changes

2020-03-19 16:49 UTC, facucompe approved these changes

2020-03-19 17:11 UTC, merged