[Controlador Usuario] - Create user controller
wolox-training/af-java pull request #9
Opened 2020-03-12 15:28 UTC by AleFalcon

## Summary
Create user controller with views in html5

## Trello Card
https://trello.com/c/Z5wPj4WA/21-crear-user-controller-con-las-operaciones-crud-de-user

2020-03-16 13:41 UTC, Gianni-Nicolas requested changes
Great job

2020-03-16 13:41 UTC, GNico95 commented on src/main/java/wolox/training/models/User.java
> +    @Autowired
This is not necessary

2020-03-16 13:41 UTC, GNico95 commented on src/main/java/wolox/training/models/User.java
> +    @Autowired
This is not necessary

2020-03-16 13:41 UTC, GNico95 commented on src/main/java/wolox/training/models/Book.java
> +    public void add_user(User user){
I don't think this method will be used. Once a book is automatically acquired by a user with the declared relationship, the user will be added to the book list.

2020-03-16 13:41 UTC, GNico95 commented on src/main/java/wolox/training/errors/user/UserNotFoundException.java
> +public class UserNotFoundException extends RuntimeException {
I could add this exception to the existing error handler.

2020-03-16 13:41 UTC, GNico95 commented on src/main/java/wolox/training/controllers/UserApiController.java
> +    public void delete(@RequestBody User user) {
If your search method uses username only, I don't think sending the entire book is necessary. You can send the username as @PathVariable or @RequestParam.

2020-03-16 13:41 UTC, GNico95 commented on src/main/java/wolox/training/controllers/UserApiController.java
> +    public User read(@RequestBody User user) {
The same as in the delete method.

2020-03-16 13:41 UTC, GNico95 commented on src/main/java/wolox/training/controllers/UserApiController.java
> +    public User add_book(@RequestBody User user, @RequestBody Book book) {
The same as in the delete method.

2020-03-16 13:41 UTC, GNico95 commented on src/main/java/wolox/training/controllers/UserApiController.java
> +    public User create(@RequestBody User user) {
t is considered a good practice in Api Rest not to create specific routes for each method, that is, not to have a path "api/users/create", "api/users/delete", etc.

It is enough to have the different http method to differentiate one url from another. With the same http method you are saying if it is a cration, a search, an update or a deletion, it is not necessary to write it in the url.

I recommend using the following URLs:

POST api/users

DELETE api/users

GET api/ users/{username}

PUT api/books/{username}

2020-03-18 17:39 UTC, Gianni-Nicolas requested changes

2020-03-18 17:39 UTC, GNico95 commented on src/main/java/wolox/training/controllers/UserApiController.java
> +    @GetMapping("{username}")
```suggestion
    @GetMapping("/{username}")
```

2020-03-19 15:30 UTC, Gianni-Nicolas submitted a review, later dismissed

2020-03-19 19:40 UTC, facucompe submitted a review, later dismissed
Great work

2020-03-19 19:44 UTC, facucompe approved these changes

2020-03-19 20:07 UTC, Gianni-Nicolas approved these changes

2020-03-20 14:12 UTC, merged